/**
 * Bundle the gallery server into one file with no runtime dependencies.
 *
 * The load-bearing line is the `obsidian` alias. The server reuses the plugin's
 * own package engine verbatim — `readPackage`, `verifyPackageSignature`,
 * `describeReferences`, `residualPaths`, `previewFromPackage` — because a
 * gallery that reimplements any of them is a gallery that disagrees with the
 * plugin about what a package is, and it will disagree in exactly the cases
 * that matter. Those modules sit above `src/types.ts`, which imports `Platform`
 * from `obsidian`; the alias points that import at a small stub, the same trick
 * the test suite uses.
 *
 * The result is a single `dist/index.js` that Node runs with nothing installed
 * beside it — which is what makes the Docker image two lines long and the
 * upgrade path a file copy.
 */
import esbuild from "esbuild";
import { fileURLToPath } from "node:url";
import { builtinModules } from "node:module";

const root = new URL("../", import.meta.url);

await esbuild.build({
	entryPoints: [fileURLToPath(new URL("src/index.ts", import.meta.url))],
	outfile: fileURLToPath(new URL("dist/index.js", import.meta.url)),
	bundle: true,
	platform: "node",
	format: "esm",
	target: "node22",
	// Node's own modules stay external; everything else — including the plugin's
	// engine and its two crypto dependencies — is inlined.
	external: [...builtinModules, ...builtinModules.map((m) => `node:${m}`)],
	alias: {
		obsidian: fileURLToPath(new URL("server/src/obsidian-stub.ts", root)),
	},
	logLevel: "info",
	sourcemap: false,
	minify: false,
	banner: {
		js: "/* Hearth gallery server — generated by esbuild from server/src. */",
	},
});
